name: CI

on:
  push:
    branches: [ CI ]

defaults:
  run:
    working-directory: ./flutter_calculator/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Hello world
        run: dart bin/hello_world.dart